# Week 4: Policy {.sec_wk4}

## Summary

The Sustainable Development Goals (SDGs), also known as the Global Goals, were adopted by the United Nations in 2015 as a universal call to action to end poverty, protect the planet, and ensure that by 2030 all people enjoy peace and prosperity [@2015].It is an important and challenge topic in urban planning and policy in today's era that how to build a sustainable and resilient city of the future. One of the strategies for SDGs is as follow.

> By 2030, significantly reduce the number of deaths and the number of people affected and substantially decrease the direct economic losses relative to global gross domestic product caused by disasters, including water-related disasters, with a focus on protecting the poor and people in vulnerable situations

Here, I focus on the Storm Water Management Model (SWMM) which can be able to solve the water-related disasters mentioned above. To achieve efficient storm water management, Sydney has a strategy in the *@2020b*.

> Explore options for developing artificial intelligence capabilities to drive efficient resource use, and advance the circular economy. Machine learning capabilities can analyse data collected from sensor networks to **monitor quality of urban conditions** and automate decisions. For example, a smart stormwater system could determine cleaning and maintenance schedules and identify flooding risks, or smart irrigation can help us manage water use to green the city.

This strategy not only solve the challenge of storm water management effectively, but also reduce the unnecessary cost and reuse water resource. With the identification of **potential flooding area with different level**, **differential management** can be constructed at the most essential places without the waste of cost and resource. If the infrastructure is aging or creaking, it can be modifies and responded in time with real-time monitoring of the urban condition. Green Infrastructure can also be applied together to reuse water resource and improve the quality of landscape and environment.

## Application

@tsubaki2010 developed a comprehensive method to conduct detailed inundation flow simulations for a populated area with quite complex topographical features using LiDAR (Light Detection and Ranging) data. They used detailed geospatial information including the location and shape of each building extracted from the LiDAR data to generate unstructured grid that represents the complex urban landscape, and estimated the water depth by performing different inundation simulations.

### Data

LiDAR

* Platform: Cessna C207 
* Laser scanner: ALTM3100-C (Optec) 
* Laser pulse frequency: 50 000 Hz 
* Altitude: 2000 m
* Scanning frequency: 30 Hz
* Point density: 1/m2

### Method

Here is the flow chart of data processing.

![Flow chart Source:[@tsubaki2010]](img04/flow-chart.png) {fig-tsubaki2010Framework}

In this study, the line segmentation approach, proposed by @sithole2003, is used to obtain **digital terrain model (DTM)**. This method involves the segmentation of a point-cloud followed by a classification. Based on the elevation connectivity of the neighbouring segments, the domain is classified as terrain (bare earth and attached objects such as bridges and overpasses, which connect to bare earth on one side), **detached objects** (buildings and vegetations), and unclassified area.

![Steps of LiDAR and colour data processing, Source:[@tsubaki2010]](img04/outcome.png)

Then, distinguish between vegetation and building areas by Delaunay triangulation and generate unstructured grid

![Building extraction and unstructured grid generation, Source:[@tsubaki2010]](img04/outcome2.png)

### Outcome

![Digital model, Source:[@tsubaki2010]](img04/flood_model.png)

![Inundation flow simulation, Source:[@tsubaki2010]](img04/inundation-flow-simulation.png)

## Reflection

In this era of information, city governance pursue high efficiency and environmental sustainability, so that remote sensing plays an essential role to provide monitoring information about city's condition. 

With the support of remote sensing data, people can predict disasters, monitor pollution and estimate resources, and then conduct relevant policy to solve it, which help to reduce the cost brought by future environmental pressure. 

In the case of flooding simulation [@tsubaki2010], LiDAR data provides a high exquisite precision to predict potential flooding areas or urban water logging places. For government, massive construction of grey infrastructure and flooding prevention can be put forward in these areas, which can make use of those public expenditure and reduce the potential risk. 

And this application of LiDAR data can partially reach the storm water management policy of Sydney. With the identification of potential flooding area with different level, differential management can be constructed at the most essential places without the waste of cost and resource. 

However, if we want to monitor the real-time condition of urban and those infrastructure, it is doubtable that whether LiDAR data can support it or not. It might be a large amount of financial cost. And to respond the condition changing and decide automatically, machine learning and Artificial Intelligence capabilities are needed, which is a long road to expore. 
